version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.6.2
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - ./docker/elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - docker_net
  redis:
    image: redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis_data:/data
    networks:
      - docker_net
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo_data:/data/db
    networks:
      - docker_net
  cassandra:
    image: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./docker/cassandra_data:/var/lib/cassandra
    networks:
      - docker_net
  kibana:
    image: kibana:7.6.2
    hostname: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./docker/kibana_data:/usr/share/kibana/data
    networks:
      - docker_net
  logstash:
    image: logstash:7.6.2
    hostname: logstash
    volumes:
      - ./docker/logstash_data/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - docker_net
  filebeat:
    image: elastic/filebeat:7.6.2
    hostname: filebeat
    volumes:
      - ./docker/filebeat_data/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./docker/shared:/usr/share/filebeat/djangologs/
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge